version: '3.4'

services:

  meetingorganizer_postgresql:
    image: postgres:14.1

  meetingorganizer_api:
    image: ${DOCKER_REGISTRY-}meetingorganizerapi
    build:
      context: .
      dockerfile: Systems/Api/MeetingOrganizer.Api/Dockerfile
    depends_on:
      - meetingorganizer_postgresql

  meetingorganizer_identity:
    image: ${DOCKER_REGISTRY-}meetingorganizeridentity
    build:
      context: .
      dockerfile: Systems/Identity/MeetingOrganizer.Identity/Dockerfile
    depends_on:
      - meetingorganizer_postgresql
      - meetingorganizer_api