version: '3.4'

services:

  meetingorganizer_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_meetingorganizer_net
    volumes:
      - ~/.docker-conf/postgresql/data:/lib/postgresql/data

  meetingorganizer_api:
    ports:
      - "10000:8080"
    networks:
      - shared_meetingorganizer_net
    env_file:
      - env.api

  meetingorganizer_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_meetingorganizer_net
    env_file:
      - env.identity

networks:
  shared_meetingorganizer_net:
    name: meetingorganizer
    driver: bridge