version: '3.4'

services:

  meetingorganizer_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_meetingorganizer_net
    volumes:
      - ~/.docker-conf/postgresql/data:/lib/postgresql/data

  meetingorganizer_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_meetingorganizer_net
    volumes:
      - ~/.docker-conf/redis/data:/data

  meetingorganizer_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    networks:
      - shared_meetingorganizer_net
    volumes:      
      - ~/.docker-conf/rabbitmq:/var/lib/rabbitmq

  meetingorganizer_api:
    ports:
      - "10000:8080"
    networks:
      - shared_meetingorganizer_net
    volumes:      
      - .docker/api/wwwroot/images:/app/wwwroot/images
    env_file:
      - env.api

  meetingorganizer_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_meetingorganizer_net
    env_file:
      - env.identity

  meetingorganizer_worker:
    networks:
      - shared_meetingorganizer_net
    env_file:
      - env.worker

  meetingorganizer_web:
    ports:
      - "10002:8080"
    networks:
      - shared_meetingorganizer_net

networks:
  shared_meetingorganizer_net:
    name: meetingorganizer
    driver: bridge