version: '3.4'

services:

  meetingorganizer_postgresql:
    image: postgres:14.1

  meetingorganizer_redis:
    image: redis

  meetingorganizer_rabbitmq:
    image: rabbitmq:management

  meetingorganizer_api:
    image: ${DOCKER_REGISTRY-}meetingorganizerapi
    build:
      context: .
      dockerfile: Systems/Api/MeetingOrganizer.Api/Dockerfile
    depends_on:
      - meetingorganizer_postgresql
      - meetingorganizer_redis

  meetingorganizer_identity:
    image: ${DOCKER_REGISTRY-}meetingorganizeridentity
    build:
      context: .
      dockerfile: Systems/Identity/MeetingOrganizer.Identity/Dockerfile
    depends_on:
      - meetingorganizer_postgresql
      - meetingorganizer_redis
      - meetingorganizer_api

  meetingorganizer_worker:
    image: ${DOCKER_REGISTRY-}meetingorganizerworker
    build:
      context: .
      dockerfile: Systems/Worker/MeetingOrganizer.Worker/Dockerfile
    depends_on:
      - meetingorganizer_api
      - meetingorganizer_postgresql
      - meetingorganizer_rabbitmq
      - meetingorganizer_redis