version: '3.4'

services:

  meetingorganizer_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_meetingorganizer_net
    volumes:
      - ~/.docker-conf/postgresql/data:/lib/postgresql/data

  meetingorganizer.api:
    ports:
      - "10000:8080"
    networks:
      - shared_meetingorganizer_net
    env_file:
      - env.api


networks:
  shared_meetingorganizer_net:
    name: meetingorganizer
    driver: bridge